MODULE PARAMETER_MODULE
INTEGER, PARAMETER						::				PN=1000, PNA=500
REAL*8, PARAMETER						::				PI=3.1415926
REAL*8, PARAMETER						::				L=11.1D0
REAL*8, DIMENSION(1:PN, 2)				::				PP, PV
REAL*8, DIMENSION(1:PN)					::				RA				
REAL*8, DIMENSION(1:PN)					::				RIN
REAL*8, DIMENSION(1:PN)					::				COTIME
INTEGER, DIMENSION(1:PN)				::				PARTNER
REAL*8, PARAMETER						::				BIGMAX=1.0E8
INTEGER									::				MOTION_STEP
REAL*8									::				TIME


END MODULE PARAMETER_MODULE