PROGRAM MAIN
INTEGER, PARAMETER	::				PN=1000
REAL*8, PARAMETER	::				PI=3.1415926
INTEGER				::				I, SI, IT, AC, K1
REAL*8				::				AS, PACKPHI, LL, VL, K2
REAL*8				::				CRP, LCRP

TYPE :: NODE
	INTEGER				::				SE
	TYPE(NODE),POINTER	::				NEXT
END TYPE NODE

TYPE(NODE), POINTER			::				HEAD, VER, TVER

REAL*8, DIMENSION(1:PN, 2)	::				PP
REAL*8, DIMENSION(1:PN)		::				RA
REAL*8, DIMENSION(:, :), ALLOCATABLE	::		TPP
REAL*8, DIMENSION(:), ALLOCATABLE		::		TRA



CALL RANDOM_SEED()

CRP=0.75D0; LCRP=0.749D0
LL=11.1D0

OPEN(1, FILE='INI_0.70_11.1.TXT')
READ(1, '(F25.16)') K2
DO I=1, PN
	READ(1, '(I5, 3F25.16)') K1, RA(I), PP(I, :)
ENDDO
CLOSE(1)

RA=RA-0.000001D0

AS=0.0D0
DO I=1, PN
	AS=AS+PI*(RA(I)**2.)
ENDDO
PACKPHI=AS/(LL*LL)
PRINT*, PACKPHI

NULLIFY(HEAD)
DO I=1, PN
	IF (I==1) THEN
		ALLOCATE(HEAD)
		HEAD%SE=I
		NULLIFY(HEAD%NEXT)
	ELSE
		VER=>HEAD
		ALLOCATE(HEAD)
		HEAD%SE=I
		HEAD%NEXT=>VER
	ENDIF
ENDDO

SI=PN

DO

100	CALL RANDOM_NUMBER(R)
	IT=DBLE(SI)*R+1
	IF (IT==1) THEN
		II=HEAD%SE
		PA_PACKPHI=PI*(RA(II)**2.)/(LL*LL)
		TPACKPHI=PACKPHI-PA_PACKPHI
		IF (TPACKPHI>=CRP) THEN
			VER=>HEAD%NEXT
			DEALLOCATE(HEAD)
			HEAD=>VER
			PACKPHI=TPACKPHI
			SI=SI-1
		ELSEIF (TPACKPHI>LCRP.AND.TPACKPHI<CRP) THEN
			VER=>HEAD%NEXT
			DEALLOCATE(HEAD)
			HEAD=>VER
			PACKPHI=TPACKPHI
			EXIT			
		ELSEIF (TPACKPHI<=LCRP) THEN
			GO TO 100
		ENDIF
	ELSE
		VER=>HEAD
		DO I=2, IT	
			TVER=>VER
			VER=>VER%NEXT
		ENDDO
		II=VER%SE
		PA_PACKPHI=PI*(RA(II)**2.)/(LL*LL)
		TPACKPHI=PACKPHI-PA_PACKPHI		
		IF (TPACKPHI>=CRP) THEN
			IF (.NOT.ASSOCIATED(VER%NEXT)) THEN
				NULLIFY(TVER%NEXT)
				DEALLOCATE(VER)
			ELSE
				TVER%NEXT=>VER%NEXT
				DEALLOCATE(VER)
			ENDIF
			PACKPHI=TPACKPHI
			SI=SI-1
		ELSEIF (TPACKPHI>LCRP.AND.TPACKPHI<CRP) THEN
			IF (.NOT.ASSOCIATED(VER%NEXT)) THEN
				NULLIFY(TVER%NEXT)
				DEALLOCATE(VER)
			ELSE
				TVER%NEXT=>VER%NEXT
				DEALLOCATE(VER)
			ENDIF
			PACKPHI=TPACKPHI
			EXIT						
		ELSEIF (TPACKPHI<=LCRP) THEN
			GO TO 100
		ENDIF
	ENDIF

ENDDO

AC=0
VER=>HEAD
DO
	IF (.NOT.ASSOCIATED(VER%NEXT)) THEN
		AC=AC+1
		EXIT
	ELSE
		AC=AC+1
		VER=>VER%NEXT
	ENDIF
ENDDO

ALLOCATE(TPP(AC, 2))
ALLOCATE(TRA(AC))

AC=0
VER=>HEAD
DO

	IF (.NOT.ASSOCIATED(VER%NEXT)) THEN
		AC=AC+1
		TPP(AC, :)=PP(VER%SE, :)
		TRA(AC)=RA(VER%SE)
		EXIT
	ELSE
		AC=AC+1
		TPP(AC, :)=PP(VER%SE, :)
		TRA(AC)=RA(VER%SE)
		VER=>VER%NEXT
	ENDIF
ENDDO

AS=0.0D0
DO I=1, AC
	AS=AS+PI*(TRA(I)**2.)/(LL*LL)
ENDDO

PRINT*, AS

OPEN(1, FILE='INI_.TXT')
DO I=AC, 1, -1
	WRITE(1, '(I5, 4F25.16)') AC-I+1, TRA(I), TPP(I, :)
ENDDO
CLOSE(1)

END PROGRAM MAIN